theme: jekyll-theme-minimal
title: Guic Pilimni
description: Bookmark this to keep an eye on my project updates!
<a href="https://github.com/lukynn1/guic_pilimni/archive/refs/heads/main.zip">guic_pilimni.lukynn1.zip</a>
